// Latch — the friendly, private clipboard for macOS.
// Copyright (C) 2026 Milad Nalbandi
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

import Foundation

/// Read-side abstraction over `NSPasteboard`, so the monitor can be driven by a fake
/// in tests. The only concrete implementation is `SystemPasteboard`.
public protocol PasteboardReading: AnyObject {
    /// Monotonic counter that bumps on every system-wide pasteboard write.
    var changeCount: Int { get }
    /// Raw type identifiers currently on the pasteboard (e.g. "public.utf8-plain-text").
    func availableTypes() -> [String]
    func string(forType type: String) -> String?
    func data(forType type: String) -> Data?
}

/// Write-side abstraction, used by copy-back (feature 08).
public protocol PasteboardWriting: AnyObject {
    func write(_ item: ClipItem)
}

/// Supplies the name of the app the user is copying from (feature 01).
public protocol SourceProviding: AnyObject {
    func currentSourceName() -> String?
}

// MARK: - Well-known pasteboard type identifiers

public enum PasteboardType {
    public static let plainText = "public.utf8-plain-text"
    public static let rtf = "public.rtf"
    public static let fileURL = "public.file-url"
    public static let tiff = "public.tiff"
    public static let png = "public.png"

    /// Concealed / transient hints honored by the privacy filter (feature 02).
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
}
