// Latch — the friendly, private clipboard for macOS.
// Copyright (C) 2026 Milad Nalbandi
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

import Foundation

/// Decides whether a pasteboard entry should be skipped entirely (never captured,
/// stored, or persisted) based on the `org.nspasteboard.*` type hints that password
/// managers and privacy-aware apps set. See specs/02-privacy-filter.
public struct PrivacyFilter {
    /// Types that are always skipped.
    public static let alwaysSkip: Set<String> = [
        PasteboardType.transient,
        PasteboardType.autoGenerated,
    ]

    /// The concealed type is skipped while `ignorePasswords` is enabled (default).
    public var ignorePasswords: Bool

    public init(ignorePasswords: Bool = true) {
        self.ignorePasswords = ignorePasswords
    }

    /// True when the entry should NOT be captured.
    public func shouldSkip(types: [String]) -> Bool {
        let set = Set(types)
        if !PrivacyFilter.alwaysSkip.isDisjoint(with: set) { return true }
        if ignorePasswords, set.contains(PasteboardType.concealed) { return true }
        return false
    }
}
