// Latch — the friendly, private clipboard for macOS.
// Copyright (C) 2026 Milad Nalbandi
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option)
// any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

import XCTest
@testable import LatchEngine

final class PrivacyFilterTests: XCTestCase {
    func testSkipsConcealedTransientAutogenerated() {
        let f = PrivacyFilter()
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.concealed]))
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.transient]))
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.autoGenerated]))
    }

    func testAllowsOrdinaryTypes() {
        let f = PrivacyFilter()
        XCTAssertFalse(f.shouldSkip(types: [PasteboardType.plainText, PasteboardType.rtf]))
    }

    func testMixedTypesSkip() {
        let f = PrivacyFilter()
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.plainText, PasteboardType.concealed]))
    }

    func testIgnorePasswordsToggleOff() {
        var f = PrivacyFilter(ignorePasswords: false)
        XCTAssertFalse(f.shouldSkip(types: [PasteboardType.concealed]))
        // Transient still always skipped.
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.transient]))
        f.ignorePasswords = true
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.concealed]))
    }
}
