import XCTest
@testable import LatchEngine

final class PrivacyFilterTests: XCTestCase {
    func testSkipsConcealedTransientAutogenerated() {
        let f = PrivacyFilter()
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.concealed]))
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.transient]))
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.autoGenerated]))
    }

    func testAllowsOrdinaryTypes() {
        let f = PrivacyFilter()
        XCTAssertFalse(f.shouldSkip(types: [PasteboardType.plainText, PasteboardType.rtf]))
    }

    func testMixedTypesSkip() {
        let f = PrivacyFilter()
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.plainText, PasteboardType.concealed]))
    }

    func testIgnorePasswordsToggleOff() {
        var f = PrivacyFilter(ignorePasswords: false)
        XCTAssertFalse(f.shouldSkip(types: [PasteboardType.concealed]))
        // Transient still always skipped.
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.transient]))
        f.ignorePasswords = true
        XCTAssertTrue(f.shouldSkip(types: [PasteboardType.concealed]))
    }
}
