import Foundation

/// Decides whether a pasteboard entry should be skipped entirely (never captured,
/// stored, or persisted) based on the `org.nspasteboard.*` type hints that password
/// managers and privacy-aware apps set. See specs/02-privacy-filter.
public struct PrivacyFilter {
    /// Types that are always skipped.
    public static let alwaysSkip: Set<String> = [
        PasteboardType.transient,
        PasteboardType.autoGenerated,
    ]

    /// The concealed type is skipped while `ignorePasswords` is enabled (default).
    public var ignorePasswords: Bool

    public init(ignorePasswords: Bool = true) {
        self.ignorePasswords = ignorePasswords
    }

    /// True when the entry should NOT be captured.
    public func shouldSkip(types: [String]) -> Bool {
        let set = Set(types)
        if !PrivacyFilter.alwaysSkip.isDisjoint(with: set) { return true }
        if ignorePasswords, set.contains(PasteboardType.concealed) { return true }
        return false
    }
}
